### ISSUE TITLE
关闭应用, 应用无响应一段时间后闪退。

### ISSUE THREAD

**Issue by JemmyWang94** [hlwhl/webview_cef#135] opened 2024-08-12 08:02 UTC
[0812/155320.365:INFO:CONSOLE(464)] "[vite] hot updated: /src/views/markets/subscription/components/subscription-apply.tsx", source: http://192.1.2.97:3000/@vite/client (464)
[0812/155320.366:INFO:CONSOLE(464)] "[vite] hot updated: /src/assets/tailwind.css", source: http://192.1.2.97:3000/@vite/client (464)
[0812/155332.437:FATAL:shutdown_checker.cc(30)] Check failed: !IsCefShutdown(). Object reference incorrectly held at CefShutdown
Lost connection to device.

**Comment by SinyimZhi** [comment] 2024-08-12 10:07
This is caused by not calling CefShutdown when closing the application. Under normal circumstances, the application should ensure that CefShutdown is called before exiting itself to prevent any residual processes related to Cef. We have provided [an interface](https://github.com/hlwhl/webview_cef/blob/ab3e19ee3f9d83334855d3969067d924671e7b24/lib/src/webview_manager.dart#L150) for notifying the C++ side to call CefShutdown, but the user of the plugin needs to ensure that the interface can be called properly (considering that the interface passes messages through the method channel, and if the method channel is closed in advance, it may cause the call to fail).

**Closed** 2024-09-18 08:57 UTC
